import fs from 'node:fs/promises';
import path from 'node:path';
import { pathExist } from './fs.js';

const generatedFileComment = `/**
 * This file was automatically generated by @goatjs/core
 * Do not modify it manually
 */`;

interface Params {
  inputFolder: string;
  outputFolder: string;
  files: string[];
}

export const copyFilesFromFolder = async ({ files, inputFolder, outputFolder }: Params) => {
  if (!(await pathExist(outputFolder))) {
    await fs.mkdir(outputFolder, { recursive: true });
  }

  for (const file of files) {
    const buf = await fs.readFile(path.join(inputFolder, file));
    const content = `${generatedFileComment}\n\n${buf.toString()}`;
    await fs.writeFile(path.join(outputFolder, file), content);
  }
};
