import fs from 'node:fs/promises';
import path from 'node:path';
import { pathExist } from './fs.js';

const generatedFileComment = `/**
 * This file was automatically generated by @goatjs/core
 * Do not modify it manually
 */`;

interface Params {
  inputFolder: string;
  outputFolder: string;
  files: string[] | '*';
}

const withComment = new Set(['js', 'ts', 'tsx', 'jsx', 'cjs', 'mjs', 'cts']);

export const copyFilesFromFolder = async ({ files, inputFolder, outputFolder }: Params) => {
  if (!(await pathExist(outputFolder))) {
    await fs.mkdir(outputFolder, { recursive: true });
  }

  const array = files === '*' ? await fs.readdir(inputFolder) : files;

  for (const file of array) {
    const buf = await fs.readFile(path.join(inputFolder, file));
    const extname = path.extname(file).slice(1);
    const isJs = withComment.has(extname);
    const content = isJs ? `${generatedFileComment}\n\n${buf.toString()}` : buf.toString();
    await fs.writeFile(path.join(outputFolder, file), content);
  }
};
